### ISSUE TITLE
Upnp UDP timeout

### ISSUE THREAD

**Issue by peerchemist** [mably/ppcd#10]
Upnp has it's quirks sometimes. This needs more triage however.

> ppcd[24273]: 13:24:01 2014-12-02 [WRN] SRVR: Can't discover upnp: write udp4: i/o timeout

**Comment by mably** [comment]
This issue was moved to ppcsuite/ppcd#4

**Comment by mably** [comment]
This issue was moved to ppcsuite/ppcd#14
