### ISSUE TITLE
Example .service file for systemd integration

### ISSUE THREAD

**Issue by peerchemist** [mably/ppcd#12]
[Unit]
Description=PPCD
After=network.target
Conflicts=ppcoind.service

[Install]
WantedBy=multi-user.target

[Service]
User=ppcd
Group=ppcd
Restart=always
RestartSec=15
PIDFile=/run/ppcd/ppcd.pid
ExecStart=/usr/bin/ppcd \
		--configfile=/etc/ppcd/ppcd.conf \
		--datadir=/var/lib/ppcd \
		--debuglevel=info

PrivateTmp=true
PrivateDevices=yes
ProtectSystem=full
ProtectHome=yes
NoNewPrivileges=yes

**Comment by mably** [comment]
This issue was moved to ppcsuite/ppcd#3

**Comment by mably** [comment]
This issue was moved to ppcsuite/ppcd#13
