### ISSUE TITLE
[Feature request] add option to create SSl certificate 

### ISSUE THREAD

**Issue by peerchemist** [mably/ppcd#13]
Desired functionality would be to have command line option to create certificate in desired directory and quit.

> ppcd --createrpccert /etc/ppcd/

Ppcd would then create rpc.cert in /etc/ppcd/ and quit gracefully.
This would allow more elegant solution to enable RPC communication with Ppcd when it is being run on multi-user system. Otherwise, root user is supposed to copy rpc.cert to each user's home directory.

**Comment by mably** [comment]
This issue was moved to ppcsuite/ppcd#12
