### ISSUE TITLE
bad nodes

### ISSUE THREAD

**Issue by kac-** [mably/ppcd#3]
We're currently trying to deal with them by old version rejection which is still buggy - https://github.com/mably/ppcd/commit/45d4064dc0a652f0e12e0160f8a4117c257f1976

Bad node, good for test, is i.e. `184.106.176.25:9901`.

Peercoin Core marks them as misbehaving, due to `ERROR: ProcessBlock() : block with too little proof-of-stake` http://tny.cz/2c52696c (bottom of log).

[server.go](https://github.com/mably/ppcd/blob/master/server.go#L712) has `func (s *server) BanPeer(p *peer){}` but btcd doesn't make use of it.

**Comment by mably** [comment]
This issue was moved to ppcsuite/ppcd#9
